remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Lab 3 
description: In this lab we practiced more javascript coding concepts such as refactoring, destructuring, and arrow functions. We learned different syntax’s in objects and arrays.
